# This runs pyright and black on your code when a commit is pushed or a pull request is opened, reopned, or sync'd.
# You can see easily confiurable options in the `matrix` section. (starts on line 18)
# The `checked-packages` option should be a list of packages seperated by a space.
# Ex: ["folder_1 folder_2 folder_3"]

name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        checked-packages: ["."]
        pyright-version: ['1.1.289']
        node-version: ['16']

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel black requests
          pip install -U -r requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: ${{ pyright-version   }}
          warnings: false
          no-comments: ${{ matrix.python-version != '3.x' }}

      - name: Run black
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          black --check ${{ matrix.checked-packages }}